name: Generate HTML with Node.js

on:
  push:
    branches:
      - master

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Change this to your required Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install required package
        run: npm install resumed jsonresume-theme-onepage-plus

      - name: Run command to generate HTML
        run: npx resumed render resume.json --theme jsonresume-theme-onepage-plus > output.html  # Replace with actual command

      - name: Upload generated HTML file
        uses: actions/upload-artifact@v4
        with:
          name: generated-html
          path: output.html
